GET http://localhost:3000

###
POST  http://localhost:3000/user/register
Content-Type: application/json

{
    "email" : "longcv1@gmail.com",
    "password": "1234651"
}

###
POST  http://localhost:3000/user/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTA1ZGVjYzYxZmE3NWI1ZDlhNzRmYzYiLCJpYXQiOjE2OTQ4ODYxNjgsImV4cCI6MTcyNjQ0Mzc2OH0.bdgubl9-ZbpJFYyn_faq6FlozIdNx7sONuGXfmlRexM
###
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "email" : "longcv1@gmail.com",
    "password": "1234651"
}

###
GET  http://localhost:3000/user/getlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTA1ZGVjYzYxZmE3NWI1ZDlhNzRmYzYiLCJpYXQiOjE2OTQ4ODgwODcsImV4cCI6MTY5NDg5MTY4N30.9szexu-KUhHNFLOYBdcAH4CRVjCmZybggiG0fIp8cjc
###
POST  http://localhost:3000/user/logout





